### ISSUE TITLE
Configurable save location

### ISSUE THREAD

**Issue by MatthiasKunnen** [Vindicta-Team/FileXT#4]
Would it be possible to make the save location editable? Saving it in the mod's folder makes it susceptible to overwrites for example when you update mods by copying files over.

**Comment by Sparker95** [comment]
I'd prefer it to be restricted within the mod folder to prevet access to parent folder of the current folder.
I think that when you copy one folder and the destination already has a folder with same name, it lets you combine folders instead of overriding files.

I was thinking where it should save the files initially when I was making this addon. I was recommended by a tech person at an arma hosting company that I should save the files into the mod folder to make mod backup and migration easier.

**Comment by MatthiasKunnen** [comment]
I see. I prefer to have one folder where generated/redownloadable data is kept (such as the game and mods) and then other folders for configs, saves etc. That way if when backup the config and save folder I know I have everything. I do understand your point though as mods might be custom and therefore need to be backed up too.

I'll just need to remember not to `rsync --delete`.
